### PR TITLE
feat: add analytics

### PR DESCRIPTION
**Pull request by Fini04**
add analytics

### CODE REVIEW

**Comment by tametsi** [comment]
nice addition, thanks a lot;
would love to see 2 more things:

- description of the axes of the graph
- the selected runner in the `select` tag should be selected after you open the analytics page and not only depend on a change in the `select` tag

**Comment by tametsi** [comment]
the graph looks cool, however we would love to see:

- if there are no runners the whole select dialog should be replaced by an info message
- if the selected runner is `null`, the first runner should be selected automatically (e.g. you delete the currently selected runner)

**Review by xXjojaXx — CHANGES_REQUESTED** [review]
1. Remove unnecessary optional chaining operators (?.)
2. Replace `rounds.all.length` with shorter syntax `rounds.count`
3. Don't make use of the tables `thin` class out of it's logical context

**Review by xXjojaXx — APPROVED** [review]
Finally🎉

**Pull request merged**
